# Generated by Django 2.2.2 on 2019-06-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
